<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260721081312 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE variant_stakes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, min_buy_in INT NOT NULL, max_buy_in INT NOT NULL, variant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_33E234D63B69A9AF ON variant_stakes (variant_id)');
        $this->addSql('ALTER TABLE variant_stakes ADD CONSTRAINT FK_33E234D63B69A9AF FOREIGN KEY (variant_id) REFERENCES variant (variant_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE variant ALTER starting_timer SET DEFAULT 30');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE variant_stakes DROP CONSTRAINT FK_33E234D63B69A9AF');
        $this->addSql('DROP TABLE variant_stakes');
        $this->addSql('ALTER TABLE variant ALTER starting_timer DROP DEFAULT');
    }
}
