<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260516124344 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rank VARCHAR(10) NOT NULL, symbol VARCHAR(10) NOT NULL, variant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_161498D33B69A9AF ON card (variant_id)');
        $this->addSql('CREATE TABLE phase (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, priority INT NOT NULL, additionnal_properties JSON NOT NULL, type VARCHAR(255) NOT NULL, timeout INT DEFAULT NULL, table_rules_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B1BDD6CB6BD4BC94 ON phase (table_rules_id)');
        $this->addSql('CREATE TABLE "user" (user_id UUID NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (user_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON "user" (username)');
        $this->addSql('CREATE TABLE variant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, max_players INT NOT NULL, table_type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE card ADD CONSTRAINT FK_161498D33B69A9AF FOREIGN KEY (variant_id) REFERENCES variant (id)');
        $this->addSql('ALTER TABLE phase ADD CONSTRAINT FK_B1BDD6CB6BD4BC94 FOREIGN KEY (table_rules_id) REFERENCES variant (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE card DROP CONSTRAINT FK_161498D33B69A9AF');
        $this->addSql('ALTER TABLE phase DROP CONSTRAINT FK_B1BDD6CB6BD4BC94');
        $this->addSql('DROP TABLE card');
        $this->addSql('DROP TABLE phase');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE variant');
    }
}
