<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260711161735 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bankroll (bankroll_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount INT NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (bankroll_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9C0FA5AA76ED395 ON bankroll (user_id)');
        $this->addSql('CREATE TABLE "table" (table_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, variant_id INT NOT NULL, PRIMARY KEY (table_id))');
        $this->addSql('CREATE INDEX IDX_F6298F463B69A9AF ON "table" (variant_id)');
        $this->addSql('CREATE TABLE table_players (amount INT NOT NULL, user_id UUID NOT NULL, table_id INT NOT NULL, PRIMARY KEY (user_id, table_id))');
        $this->addSql('CREATE INDEX IDX_247D02A9A76ED395 ON table_players (user_id)');
        $this->addSql('CREATE INDEX IDX_247D02A9ECFF285C ON table_players (table_id)');
        $this->addSql('ALTER TABLE bankroll ADD CONSTRAINT FK_9C0FA5AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (user_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "table" ADD CONSTRAINT FK_F6298F463B69A9AF FOREIGN KEY (variant_id) REFERENCES variant (variant_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE table_players ADD CONSTRAINT FK_247D02A9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (user_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE table_players ADD CONSTRAINT FK_247D02A9ECFF285C FOREIGN KEY (table_id) REFERENCES "table" (table_id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bankroll DROP CONSTRAINT FK_9C0FA5AA76ED395');
        $this->addSql('ALTER TABLE "table" DROP CONSTRAINT FK_F6298F463B69A9AF');
        $this->addSql('ALTER TABLE table_players DROP CONSTRAINT FK_247D02A9A76ED395');
        $this->addSql('ALTER TABLE table_players DROP CONSTRAINT FK_247D02A9ECFF285C');
        $this->addSql('DROP TABLE bankroll');
        $this->addSql('DROP TABLE "table"');
        $this->addSql('DROP TABLE table_players');
    }
}
